name: PR Auto-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v1

      - name: Install Dependancies
        run: ./install.sh

      - name: Build
        run: ./build.sh